# Generated by Django 3.0.5 on 2020-07-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Bitcoin/Crypto', 'Bitcoin/Crypto'), ('Savings', 'Savings'), ('Checking', 'Checking'), ('Bitcoin/Crypto', 'Bitcoin/Crypto'), ('Stocks', 'Stocks'), ('Mutual Funds', 'Mutual Funds'), ('Bank CDs', 'Bank CDs'), ('Real Estate', 'Real Estate'), ('Business', 'Business'), ('Salary/Wages', 'Salary/Wages')], max_length=60)),
                ('down', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Mortgage/Rent', 'Mortgage/Rent'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Food/Groceries', 'Food/Groceries'), ('Vehicle', 'Vehicle'), ('Health/Wellness', 'Health/Wellness'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Donations/Charity', 'Donations/Charity'), ('Taxes', 'Taxes'), ('Fees/Fines', 'Fees/Fines'), ('Other', 'Other'), ('RE Debt Service', 'RE Debt Service')], max_length=60)),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Salary/Wages', 'Salary/Wages'), ('Interest', 'Interest'), ('Dividends', 'Dividends'), ('Real Estate', 'Real Estate'), ('Business', 'Business')], max_length=60)),
                ('amount', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_account', models.CharField(choices=[('Bitcoin/Crypto', 'Bitcoin/Crypto'), ('Checking', 'Checking'), ('Savings', 'Savings'), ('Stocks', 'Stocks'), ('Mutal Funds', 'Mutal Funds'), ('Bank CDs', 'Bank CDs'), ('Real Estate', 'Real Estate'), ('Business', 'Business'), ('Salary/Wages', 'Salary/Wages')], max_length=30)),
                ('to_account', models.CharField(choices=[('Mortgage/Rent', 'Mortgage/Rent'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Food/Groceries', 'Food/Groceries'), ('Vehicle', 'Vehicle'), ('Health/Wellness', 'Health/Wellness'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Donations/Charity', 'Donations/Charity'), ('Taxes', 'Taxes'), ('Fees/Fines', 'Fees/Fines'), ('Other', 'Other'), ('RE Debt Service', 'RE Debt Service')], max_length=30)),
                ('amount', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Home Mortgage', 'Home Mortgage'), ('School Loans', 'School Loans'), ('Car Loans', 'Car Loans'), ('Credit Cards', 'Credit Cards'), ('Retaill Debt', 'Retail Debt'), ('RE Mortgages', 'RE Mortgages'), ('Business Debts', 'Business Debts'), ('Bank Loans', 'Bank Loans')], max_length=60)),
                ('amount', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=256)),
                ('url', models.CharField(default='', max_length=256)),
                ('cost', models.CharField(max_length=30)),
                ('down', models.CharField(max_length=30)),
                ('mortgage', models.CharField(max_length=30)),
                ('cash_flow', models.CharField(max_length=30)),
                ('coc', models.CharField(default='', max_length=13)),
                ('irr', models.CharField(default='', max_length=13)),
                ('ask', models.CharField(default='', max_length=30)),
                ('sqft', models.CharField(default='', max_length=30)),
                ('units', models.CharField(default='', max_length=30)),
                ('ave_rent', models.CharField(default='', max_length=30)),
                ('vacancy_rate', models.CharField(default='', max_length=30)),
                ('other_income', models.CharField(default='', max_length=30)),
                ('repairs', models.CharField(default='', max_length=30)),
                ('management', models.CharField(default='', max_length=30)),
                ('taxes', models.CharField(default='', max_length=30)),
                ('insurance', models.CharField(default='', max_length=30)),
                ('wages', models.CharField(default='', max_length=30)),
                ('utilities', models.CharField(default='', max_length=30)),
                ('gen_admin', models.CharField(default='', max_length=30)),
                ('professional_fees', models.CharField(default='', max_length=30)),
                ('advertising', models.CharField(default='', max_length=30)),
                ('cap_x', models.CharField(default='', max_length=30)),
                ('other', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
