# Generated by Django 3.0.5 on 2020-06-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='source',
            field=models.CharField(choices=[('Bitcoin/Crypto', 'Bitcoin/Crypto'), ('Savings', 'Savings'), ('Checking', 'Checking'), ('Bitcoin/Crypto', 'Bitcoin/Crypto'), ('Stocks', 'Stocks'), ('Mutual Funds', 'Mutual Funds'), ('Bank CDs', 'Bank CDs'), ('Real Estate', 'Real Estate'), ('Business', 'Business')], max_length=60),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('Mortgage/Rent', 'Mortgage/Rent'), ('Utilities', 'Utilities'), ('Insurances', 'Insurances'), ('Food/Groceries', 'Food/Groceries'), ('Vehicle(s)', 'Vehicle(s)'), ('Health/Wellness', 'Health/Wellness'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Donations/Charity', 'Donations/Charity'), ('Taxes', 'Taxes'), ('Fees/Fines', 'Fees/Fines'), ('Other', 'Other'), ('RE Debt Service', 'RE Debt Service')], max_length=60),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='to_account',
            field=models.CharField(choices=[('Mortgage/Rent', 'Mortgage/Rent'), ('Utilities', 'Utilities'), ('Insurances', 'Insurances'), ('Food/Groceries', 'Food/Groceries'), ('Vehicle(s)', 'Vehicle(s)'), ('Health/Wellness', 'Health/Wellness'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Donations/Charity', 'Donations/Charity'), ('Taxes', 'Taxes'), ('Fees/Fines', 'Fees/Fines'), ('Other', 'Other'), ('RE Debt Service', 'RE Debt Service')], max_length=30),
        ),
    ]
