# Generated by Django 3.0.5 on 2020-07-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='advertising',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='ask',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='ave_rent',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='cap_x',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='cash_flow',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='coc',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='down',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='gen_admin',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='irr',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='management',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='mortgage',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='other',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='other_income',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='professional_fees',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='repairs',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='units',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='url',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='utilities',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='vacancy_rate',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='wages',
        ),
    ]
