# Generated by Django 3.0.5 on 2020-07-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200705_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='advertising',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='ask',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='ave_rent',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='cap_x',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='cash_flow',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='coc',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='cost',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='down',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='gen_admin',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='heading',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='insurance',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='irr',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='management',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='mortgage',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='other',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='other_income',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='professional_fees',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='repairs',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sqft',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='taxes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='units',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='utilities',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='vacancy_rate',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='wages',
            field=models.CharField(default='', max_length=30),
        ),
    ]
