# Generated by Django 3.0.5 on 2020-06-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200625_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='coc',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='irr',
            field=models.CharField(default='', max_length=13),
        ),
    ]
